export const properties = [
  {
    id: 1,
    image:
      "https://tse1.mm.bing.net/th?id=OIP.NiLdfIoEGCD7uKJblPQyuQHaEK&pid=Api&P=0",
    name: "Palm harbor",
    price: 2000,
    address: "Palm harbor, mumbai, India",
    location: "mumbai",
    popular: true,
    date: "2022-09-20",
    beds: 3,
    bathrooms: 2,
    area: "2X7 m",
    type: "bungalows",
  },
  {
    id: 2,
    image:
      "https://images.unsplash.com/photo-1502993100359-6e0cee23764d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=326&q=80",
    name: "Eco Agency",
    price: 5000,
    address: "Eco Agency, mumbai, India",
    location: "mumbai",
    popular: false,
    date: "2022-09-21",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "tents",
  },
  {
    id: 3,
    image:
      "https://www.thespruce.com/thmb/PiFNpIGAP7R8ZglZeCV40P9lyXE=/941x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-523075374-8d27b929fdfc4702aab5c73f821a65de.jpg",
    name: "Full Circle",
    price: 9000,
    address: "Full Circle, mumbai, India",
    location: "mumbai",
    popular: true,
    date: "2022-09-18",
    beds: 4,
    bathrooms: 3,
    area: "6X7 m",
    type: "bungalows",
  },
  {
    id: 4,
    image:
      "https://www.thehousedesigners.com/images/plans/EXB/bulk/8662/1302NTr3.jpg",
    name: "Kale Realty",
    price: 200,
    address: "Kale Realty, surat, India",
    location: "surat",
    popular: true,
    date: "2022-09-18",
    beds: 1,
    bathrooms: 1,
    area: "2X7 m",
    type: "bungalows",
  },
  {
    id: 5,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh8fbR73XCwL8BcaJYcXBUkE_JXj0Xr2DVBA&usqp=CAU",
    name: "Real Living",
    price: 100,
    address: "Real Living, surat, India",
    location: "surat",
    popular: false,
    date: "2022-09-17",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "flats",
  },
  {
    id: 6,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDcpMYFWtK2zhBwaf2vH-aEcsRBJTOvsrFVg&usqp=CAU",
    name: "The Trophy Group",
    price: 5000,
    address: "The Trophy Group, bangalore, India",
    location: "bangalore",
    popular: true,
    date: "2022-09-29",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "flats",
  },
  {
    id: 7,
    image:
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    name: "Modern Realty",
    price: 200,
    address: "Modern Realty, bangalore, India",
    location: "bangalore",
    popular: true,
    date: "2022-09-28",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "tents",
  },
  {
    id: 8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQRtchuw4GAtw8115nwrWhLQa1J_wwiLI-gw&usqp=CAU",
    name: "My Dream Home",
    price: 1000,
    address: "My Dream Home, ahmedabad, India",
    location: "ahmedabad",
    popular: false,
    date: "2022-09-29",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "bungalows",
  },
  {
    id: 9,
    image:
      "https://images.unsplash.com/photo-1470246973918-29a93221c455?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80",
    name: "Rapid Realty",
    price: 300,
    address: "Rapid Realty, ahmedabad, India",
    location: "ahmedabad",
    popular: false,
    date: "2022-09-25",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "tents",
  },
  {
    id: 10,
    image:
      "https://images.unsplash.com/photo-1606814399166-22faa3453007?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80",
    name: "Sterling One",
    price: 8000,
    address: "Sterling One, pune, India",
    location: "pune",
    popular: true,
    date: "2022-09-24",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "tents",
  },
  {
    id: 11,
    image:
      "https://is1-3.housingcdn.com/4f2250e8/630e4454ccb925b8bce80f89e65964bb/v0/fs/sai_madhura_flats-madipakkam-chennai-vishaka_constructions.jpeg",
    name: "Big Block",
    price: 1000,
    address: "Big Block, mumbai, India",
    location: "mumbai",
    popular: true,
    date: "2022-09-23",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "flats",
  },
  {
    id: 12,
    image:
      "https://www.coldwellbankergujarat.in/wp-content/uploads/2020/02/Elevation.jpg",
    name: "Parker Realty",
    price: 500,
    address: "Parker Realty, kolkata, India",
    location: "kolkata",
    popular: false,
    date: "2022-09-22",
    beds: 4,
    bathrooms: 2,
    area: "4X7 m",
    type: "flats",
  },
];
